site_name: CodeSee Maps Documentation
nav:
  - ğŸ‘‹ Welcome:
    - Introduction: index.md
  - ğŸ›  Installation:
    - Overview: installation.md
  - ğŸš€ Using CodeSee:
    - User Guide: guide.md
    - Pull Request Maps: prs.md
  - â“ Need help?:
    - Support: support.md
theme:
  name: material
  logo: img/CS-icon-for-docs.png
  favicon: img/favicon-32x32.png
  custom_dir: overrides
  features:
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/codeseeio
copyright: Copyright &copy; 2021 CodeSee Inc
plugins:
  - mkdocs-video
